#!/usr/bin/env node

/**
 * Setup script to create .env.local file
 * Run: node setup-env.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const envPath = path.join(__dirname, '.env.local');
const examplePath = path.join(__dirname, '.env.example');

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setup() {
  console.log('\n🔧 Supabase Environment Setup\n');
  console.log('You need your Supabase credentials from:');
  console.log('https://supabase.com/dashboard/project/_/settings/api\n');

  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await question('.env.local already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Cancelled.');
      rl.close();
      return;
    }
  }

  const supabaseUrl = await question('Enter your Supabase Project URL: ');
  const supabaseKey = await question('Enter your Supabase Anon Key: ');

  if (!supabaseUrl || !supabaseKey) {
    console.log('\n❌ Both URL and Key are required!');
    rl.close();
    return;
  }

  const envContent = `# Supabase Configuration
# Generated by setup-env.js

NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseKey}
`;

  fs.writeFileSync(envPath, envContent);
  console.log('\n✅ .env.local file created successfully!');
  console.log('\n📝 Next steps:');
  console.log('1. Restart your dev server (npm run dev)');
  console.log('2. Make sure your Supabase project has the database schema set up');
  console.log('   (Run scripts/001_create_tables.sql in Supabase SQL Editor)\n');
  
  rl.close();
}

setup().catch((error) => {
  console.error('Error:', error);
  rl.close();
  process.exit(1);
});
